FILES_SIMPLE=Main ActorA  ActorB
FILES_SQUIRRELS=Cell Clock Squirrel Tracker Main RandomGenerator
FILES_FRAMEWORK=Actor ExecutionUnit Message Logger

FOLDER_SIMPLE=examples/Simple-Example
FOLDER_SQUIRRELS=examples/Squirrels-Simulation
FOLDER_FRAMEWORK=ActorFramework

MAKEFILE=$(abspath $(firstword $(MAKEFILE_LIST)))
SRC_DIR=$(dir $(MAKEFILE))
BUILD_FOLDER=$(abspath $(CURDIR))/Build/

BUILD_FOLDER_SIMPLE=$(BUILD_FOLDER)$(FOLDER_SIMPLE)
BUILD_FOLDER_SQUIRRELS=$(BUILD_FOLDER)$(FOLDER_SQUIRRELS)
BUILD_FOLDER_FRAMEWORK=$(BUILD_FOLDER)$(FOLDER_FRAMEWORK)

CODE_FOLDER_SIMPLE=$(SRC_DIR)$(FOLDER_SIMPLE)
CODE_FOLDER_SQUIRRELS=$(SRC_DIR)$(FOLDER_SQUIRRELS)
CODE_FOLDER_FRAMEWORK=$(SRC_DIR)$(FOLDER_FRAMEWORK)

SRC_FOLDER_SIMPLE=$(CODE_FOLDER_SIMPLE)/src
SRC_FOLDER_SQUIRRELS=$(CODE_FOLDER_SQUIRRELS)/src
SRC_FOLDER_FRAMEWORK=$(CODE_FOLDER_FRAMEWORK)/src

INCLUDE_FOLDER_SIMPLE=$(CODE_FOLDER_SIMPLE)/include
INCLUDE_FOLDER_SQUIRRELS=$(CODE_FOLDER_SQUIRRELS)/include
INCLUDE_FOLDER_FRAMEWORK=$(CODE_FOLDER_FRAMEWORK)/include

OBJS_SIMPLE=$(patsubst %,$(BUILD_FOLDER_SIMPLE)/%.o, $(FILES_SIMPLE))
OBJS_SQUIRRELS=$(patsubst %,$(BUILD_FOLDER_SQUIRRELS)/%.o, $(FILES_SQUIRRELS))
OBJS_FRAMEWORK=$(patsubst %,$(BUILD_FOLDER_FRAMEWORK)/%.o, $(FILES_FRAMEWORK))

LIBRARY_NAME=ActorFramework

OUTPUT_FRAMEWORK=$(BUILD_FOLDER)lib$(LIBRARY_NAME).a
OUTPUT_SQUIRRELS=$(BUILD_FOLDER)Squirrels-Simulation.out
OUTPUT_SIMPLE=$(BUILD_FOLDER)Simple-Example.out

DEPS_FRAMEWORK=$(patsubst %,$(INCLUDE_FOLDER_FRAMEWORK)/%.h, $(FILES_FRAMEWORK)) $(MAKEFILE)
DEPS_SIMPLE=$(patsubst %,$(INCLUDE_FOLDER_SIMPLE)/%.h, $(FILES_SIMPLE)) $(DEPS_FRAMEWORK)
DEPS_SQUIRRELS=$(patsubst %,$(INCLUDE_FOLDER_SQUIRRELS)/%.h, $(FILES_SQUIRRELS)) $(DEPS_FRAMEWORK)

MPICC=mpicxx
CFLAGS=-std=c++17 -g
LFLAGS=-lm
FINAL_LFLAGS=-L$(BUILD_FOLDER) -l$(LIBRARY_NAME) $(LFLAGS)

all: $(OUTPUT_SIMPLE) $(OUTPUT_SQUIRRELS)

$(BUILD_FOLDER_FRAMEWORK)/Logger.o: $(SRC_FOLDER_FRAMEWORK)/Logger.cpp $(DEPS_FRAMEWORK)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_FRAMEWORK) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_FRAMEWORK)/Actor.o: $(SRC_FOLDER_FRAMEWORK)/Actor.cpp $(DEPS_FRAMEWORK)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_FRAMEWORK) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_FRAMEWORK)/ExecutionUnit.o: $(SRC_FOLDER_FRAMEWORK)/ExecutionUnit.cpp $(DEPS_FRAMEWORK)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_FRAMEWORK) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_FRAMEWORK)/Message.o: $(SRC_FOLDER_FRAMEWORK)/Message.cpp $(DEPS_FRAMEWORK)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_FRAMEWORK) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_SQUIRRELS)/Cell.o: $(SRC_FOLDER_SQUIRRELS)/Cell.cpp $(DEPS_SQUIRRELS)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_SQUIRRELS) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_SQUIRRELS)/Main.o: $(SRC_FOLDER_SQUIRRELS)/Main.cpp $(DEPS_SQUIRRELS)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_SQUIRRELS) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_SQUIRRELS)/Clock.o: $(SRC_FOLDER_SQUIRRELS)/Clock.cpp $(DEPS_SQUIRRELS)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_SQUIRRELS) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_SQUIRRELS)/Squirrel.o: $(SRC_FOLDER_SQUIRRELS)/Squirrel.cpp $(DEPS_SQUIRRELS)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_SQUIRRELS) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_SQUIRRELS)/RandomGenerator.o: $(SRC_FOLDER_SQUIRRELS)/RandomGenerator.cpp $(DEPS_SQUIRRELS)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_SQUIRRELS) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_SQUIRRELS)/Tracker.o: $(SRC_FOLDER_SQUIRRELS)/Tracker.cpp $(DEPS_SQUIRRELS)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_SQUIRRELS) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_SIMPLE)/Main.o: $(SRC_FOLDER_SIMPLE)/Main.cpp $(DEPS_SIMPLE)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_SIMPLE) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_SIMPLE)/ActorA.o: $(SRC_FOLDER_SIMPLE)/ActorA.cpp $(DEPS_SIMPLE)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_SIMPLE) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_SIMPLE)/ActorB.o: $(SRC_FOLDER_SIMPLE)/ActorB.cpp $(DEPS_SIMPLE)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_SIMPLE) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(OUTPUT_FRAMEWORK): $(OBJS_FRAMEWORK)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER)
	ar rcu $@ $+
	ranlib $@

$(OUTPUT_SQUIRRELS): $(OBJS_SQUIRRELS) $(OBJS_FRAMEWORK) $(DEPS_SQUIRRELS) $(OUTPUT_FRAMEWORK)
	mkdir -p $(BUILD_FOLDER)
	$(MPICC) $(CFLAGS) -o $@ $(OBJS_SQUIRRELS) $(FINAL_LFLAGS)

$(OUTPUT_SIMPLE): $(OBJS_SIMPLE) $(DEPS_SIMPLE) $(OUTPUT_FRAMEWORK)
	mkdir -p $(BUILD_FOLDER)
	$(MPICC) $(CFLAGS) -o $@ $(OBJS_SIMPLE) $(FINAL_LFLAGS)

clean:
	rm -rf $(BUILD_FOLDER)*.o $(BUILD_FOLDER_SQUIRRELS)/*.o $(BUILD_FOLDER_FRAMEWORK)/*.o $(BUILD_FOLDER_SIMPLE)/*.o