FILES_SIMPLE=Main ActorA  ActorB
FILES_SQUIRRELS=Cell Clock Squirrel Tracker Main RandomGenerator
FILES_FRAMEWORK=Actor ExecutionUnit Message Logger

FOLDER_SIMPLE=Simple-Example
FOLDER_SQUIRRELS=Squirrels-Simulation
FOLDER_FRAMEWORK=Framework

MAKEFILE=$(abspath $(firstword $(MAKEFILE_LIST)))
SRC_DIR=$(dir $(MAKEFILE))
BUILD_FOLDER=$(abspath $(CURDIR))/Build/

BUILD_FOLDER_SIMPLE=$(BUILD_FOLDER)$(FOLDER_SIMPLE)
BUILD_FOLDER_SQUIRRELS=$(BUILD_FOLDER)$(FOLDER_SQUIRRELS)
BUILD_FOLDER_FRAMEWORK=$(BUILD_FOLDER)$(FOLDER_FRAMEWORK)

SRC_FOLDER_SIMPLE=$(SRC_DIR)$(FOLDER_SIMPLE)
SRC_FOLDER_SQUIRRELS=$(SRC_DIR)$(FOLDER_SQUIRRELS)
SRC_FOLDER_FRAMEWORK=$(SRC_DIR)$(FOLDER_FRAMEWORK)

OBJS_SIMPLE=$(patsubst %,$(BUILD_FOLDER_SIMPLE)/%.o, $(FILES_SIMPLE))
OBJS_SQUIRRELS=$(patsubst %,$(BUILD_FOLDER_SQUIRRELS)/%.o, $(FILES_SQUIRRELS))
OBJS_FRAMEWORK=$(patsubst %,$(BUILD_FOLDER_FRAMEWORK)/%.o, $(FILES_FRAMEWORK))

DEPS_FRAMEWORK=$(patsubst %,$(SRC_FOLDER_FRAMEWORK)/%.h, $(FILES_FRAMEWORK)) $(MAKEFILE)
DEPS_SIMPLE=$(patsubst %,$(SRC_FOLDER_SIMPLE)/%.h, $(FILES_SIMPLE)) $(DEPS_FRAMEWORK)
DEPS_SQUIRRELS=$(patsubst %,$(SRC_FOLDER_SQUIRRELS)/%.h, $(FILES_SQUIRRELS)) $(DEPS_FRAMEWORK)

OUTPUT_SQUIRRELS=$(BUILD_FOLDER)Squirrels-Simulation.out
OUTPUT_SIMPLE=$(BUILD_FOLDER)Simple-Example.out

MPICC=mpicxx
CFLAGS=-std=c++17 -g
LFLAGS=-lm

all: $(OUTPUT_SIMPLE) $(OUTPUT_SQUIRRELS)

$(BUILD_FOLDER_FRAMEWORK)/Logger.o: $(SRC_FOLDER_FRAMEWORK)/Logger.cpp $(DEPS_FRAMEWORK)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_FRAMEWORK) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_FRAMEWORK)/Actor.o: $(SRC_FOLDER_FRAMEWORK)/Actor.cpp $(DEPS_FRAMEWORK)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_FRAMEWORK) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_FRAMEWORK)/ExecutionUnit.o: $(SRC_FOLDER_FRAMEWORK)/ExecutionUnit.cpp $(DEPS_FRAMEWORK)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_FRAMEWORK) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_FRAMEWORK)/Message.o: $(SRC_FOLDER_FRAMEWORK)/Message.cpp $(DEPS_FRAMEWORK)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_FRAMEWORK) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_SQUIRRELS)/Cell.o: $(SRC_FOLDER_SQUIRRELS)/Cell.cpp $(DEPS_SQUIRRELS)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_SQUIRRELS) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_SQUIRRELS)/Main.o: $(SRC_FOLDER_SQUIRRELS)/Main.cpp $(DEPS_SQUIRRELS)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_SQUIRRELS) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_SQUIRRELS)/Clock.o: $(SRC_FOLDER_SQUIRRELS)/Clock.cpp $(DEPS_SQUIRRELS)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_SQUIRRELS) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_SQUIRRELS)/Squirrel.o: $(SRC_FOLDER_SQUIRRELS)/Squirrel.cpp $(DEPS_SQUIRRELS)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_SQUIRRELS) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_SQUIRRELS)/RandomGenerator.o: $(SRC_FOLDER_SQUIRRELS)/RandomGenerator.cpp $(DEPS_SQUIRRELS)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_SQUIRRELS) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_SQUIRRELS)/Tracker.o: $(SRC_FOLDER_SQUIRRELS)/Tracker.cpp $(DEPS_SQUIRRELS)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_SQUIRRELS) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_SIMPLE)/Main.o: $(SRC_FOLDER_SIMPLE)/Main.cpp $(DEPS_SIMPLE)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_SIMPLE) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_SIMPLE)/ActorA.o: $(SRC_FOLDER_SIMPLE)/ActorA.cpp $(DEPS_SIMPLE)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_SIMPLE) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(BUILD_FOLDER_SIMPLE)/ActorB.o: $(SRC_FOLDER_SIMPLE)/ActorB.cpp $(DEPS_SIMPLE)
	mkdir -p $(BUILD_FOLDER) $(BUILD_FOLDER_SIMPLE) 
	$(MPICC) $(CFLAGS) -c $< -o $@ $(LFLAGS)

$(OUTPUT_SQUIRRELS): $(OBJS_SQUIRRELS) $(OBJS_FRAMEWORK) $(DEPS_SQUIRRELS)
	mkdir -p $(BUILD_FOLDER)
	$(MPICC) $(CFLAGS) -o $@ $(OBJS_SQUIRRELS) $(OBJS_FRAMEWORK) $(LFLAGS)

$(OUTPUT_SIMPLE): $(OBJS_SIMPLE) $(OBJS_FRAMEWORK) $(DEPS_SIMPLE)
	mkdir -p $(BUILD_FOLDER)
	$(MPICC) $(CFLAGS) -o $@ $(OBJS_SIMPLE) $(OBJS_FRAMEWORK) $(LFLAGS)

clean:
	rm -rf $(BUILD_FOLDER)*.o $(BUILD_FOLDER_SQUIRRELS)/*.o $(BUILD_FOLDER_FRAMEWORK)/*.o $(BUILD_FOLDER_SIMPLE)/*.o